### ISSUE TITLE
Compilation error with Flutter SDK 1.17.0

### ISSUE THREAD

**Issue by guilhermeagostinelli** [dnfield/flutter_svg#341]
The following compilation errors started to happen after updating Flutter SDK version to 1.17.0 (newest stable version that has been released today):

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...

Compiler message:
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.2/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.2/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

Compiler message:
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.2/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.2/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
FAILURE: Build failed with an exception.

* Where:
Script '/home/guilherme/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/guilherme/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by dnfield** [comment]
You need to use a more recent version of flutter svg.  The change was made in v0.17.2
